# Generated by Django 3.2 on 2023-08-22 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomura_app', '0002_notification_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(blank=True, max_length=68, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, max_length=68, null=True)),
                ('percentage_return', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('amount', models.FloatField(default=0, null=True)),
                ('maximum_amount', models.FloatField(default=0, null=True)),
                ('minimum_amount', models.FloatField(default=0, null=True)),
                ('investment_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomura_app.investment')),
            ],
        ),
    ]
