# Generated by Django 3.2 on 2024-01-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomura_app', '0003_investment_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='investment_name',
        ),
        migrations.AddField(
            model_name='client',
            name='investment_plan_name',
            field=models.CharField(blank=True, default='MISSED-INFO', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment_id',
            name='investment_plan_name',
            field=models.CharField(blank=True, default='MISSED-INFO', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
